# Generated by Django 4.1.2 on 2024-06-17 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0003_arriendo_bicicleta_despacho_historialmantencion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bicicleta',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='bicicleta',
            name='marca',
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
        migrations.DeleteModel(
            name='Marca',
        ),
    ]
