# Generated by Django 4.1.2 on 2024-06-24 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0005_formapago_alter_arriendo_forma_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reparacion',
            name='bicicleta',
            field=models.CharField(max_length=100),
        ),
    ]
