# Generated by Django 4.1.2 on 2024-06-24 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0006_alter_reparacion_bicicleta'),
    ]

    operations = [
        migrations.AddField(
            model_name='bicicleta',
            name='precio_arriendo',
            field=models.FloatField(default=0.0),
        ),
    ]
